name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    uses: krosoft-dev/Krosoft.DevOps.GitHub/.github/workflows/npm-build.yml@main
    with:
      run-build: false
      run-tests: false
